import { cp, mkdir, readdir, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = resolve(root, "dist");
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
const excluded = new Set([".git", ".github", ".openai", "dist", "node_modules"]);
for (const entry of await readdir(root)) if (!excluded.has(entry)) await cp(join(root, entry), join(output, entry), { recursive: true });
console.log("Static production site built in dist/");
